import React, { useState, useEffect, useCallback, useRef } from 'react';
import { Status } from './types';
import FileUpload from './components/FileUpload';
import Loader from './components/Loader';
import ReelPlayer from './components/ReelPlayer';
import { SparklesIcon } from './components/icons';
import { GoogleGenAI, Type } from '@google/genai';

// In a real app, this would be generated by a transcription service like Whisper.
// This mock data simulates a word-level transcript for the AI to analyze.
const MOCK_TRANSCRIPT_DATA = [
    { "word": "You", "start": 0.5, "end": 0.7 }, { "word": "know,", "start": 0.7, "end": 1.1 },
    { "word": "for", "start": 1.2, "end": 1.4 }, { "word": "years", "start": 1.4, "end": 1.8 },
    { "word": "I", "start": 1.8, "end": 1.9 }, { "word": "was", "start": 1.9, "end": 2.1 },
    { "word": "just", "start": 2.1, "end": 2.4 }, { "word": "stuck.", "start": 2.4, "end": 3.0 },
    { "word": "I", "start": 3.2, "end": 3.4 }, { "word": "felt", "start": 3.4, "end": 3.7 },
    { "word": "so", "start": 3.7, "end": 4.0 }, { "word": "hopeless.", "start": 4.0, "end": 4.8 },
    { "word": "I", "start": 5.0, "end": 5.1 }, { "word": "must've", "start": 5.1, "end": 5.4 },
    { "word": "tried", "start": 5.4, "end": 5.7 }, { "word": "every", "start": 5.7, "end": 6.0 },
    { "word": "diet", "start": 6.0, "end": 6.4 }, { "word": "out", "start": 6.4, "end": 6.6 },
    { "word": "there,", "start": 6.6, "end": 7.0 }, { "word": "nothing", "start": 7.2, "end": 7.6 },
    { "word": "worked", "start": 7.6, "end": 8.0 }, { "word": "for", "start": 8.0, "end": 8.2 },
    { "word": "me.", "start": 8.2, "end": 8.5 }, { "word": "I", "start": 9.0, "end": 9.1 },
    { "word": "was", "start": 9.1, "end": 9.3 }, { "word": "probably", "start": 9.4, "end": 9.9 },
    { "word": "around", "start": 9.9, "end": 10.3 }, { "word": "100", "start": 10.4, "end": 10.8 },
    { "word": "kgs", "start": 10.8, "end": 11.2 }, { "word": "before,", "start": 11.2, "end": 11.8 },
    { "word": "my", "start": 12.5, "end": 12.7 }, { "word": "energy", "start": 12.7, "end": 13.2 },
    { "word": "was", "start": 13.2, "end": 13.4 }, { "word": "so", "start": 13.4, "end": 13.6 },
    { "word": "low.", "start": 13.6, "end": 14.0 }, { "word": "Then,", "start": 15.0, "end": 15.3 },
    { "word": "a", "start": 15.4, "end": 15.5 }, { "word": "friend", "start": 15.5, "end": 15.8 },
    { "word": "told", "start": 15.8, "end": 16.1 }, { "word": "me", "start": 16.1, "end": 16.3 },
    { "word": "about", "start": 16.3, "end": 16.6 }, { "word": "this", "start": 16.6, "end": 16.8 },
    { "word": "program.", "start": 16.8, "end": 17.5 }, { "word": "It", "start": 17.8, "end": 18.0 },
    { "word": "was", "start": 18.0, "end": 18.2 }, { "word": "a", "start": 18.2, "end": 18.3 },
    { "word": "real", "start": 18.4, "end": 18.6 }, { "word": "turning", "start": 18.6, "end": 19.0 },
    { "word": "point.", "start": 19.0, "end": 19.5 }, { "word": "The", "start": 20.5, "end": 20.7 },
    { "word": "weight", "start": 20.7, "end": 21.0 }, { "word": "just", "start": 21.0, "end": 21.3 },
    { "word": "started", "start": 21.3, "end": 21.7 }, { "word": "melting", "start": 21.7, "end": 22.1 },
    { "word": "off.", "start": 22.1, "end": 22.5 }, { "word": "In", "start": 23.0, "end": 23.2 },
    { "word": "just", "start": 23.2, "end": 23.5 }, { "word": "three", "start": 23.5, "end": 23.8 },
    { "word": "months,", "start": 23.8, "end": 24.3 }, { "word": "I", "start": 24.5, "end": 24.6 },
    { "word": "lost", "start": 24.6, "end": 25.0 }, { "word": "20", "start": 25.1, "end": 25.5 },
    { "word": "kgs!", "start": 25.5, "end": 26.0 }, { "word": "It's", "start": 26.1, "end": 26.3 },
    { "word": "incredible.", "start": 26.3, "end": 27.0 }, { "word": "Just", "start": 28.0, "end": 28.3 },
    { "word": "the", "start": 28.3, "end": 28.4 }, { "word": "other", "start": 28.4, "end": 28.7 },
    { "word": "day,", "start": 28.7, "end": 29.0 }, { "word": "my", "start": 29.1, "end": 29.3 },
    { "word": "colleague", "start": 29.3, "end": 29.9 }, { "word": "said", "start": 29.9, "end": 30.4 },
    { "word": "'Wow,", "start": 30.5, "end": 30.8 }, { "word": "you", "start": 30.8, "end": 31.0 },
    { "word": "look", "start": 31.0, "end": 31.2 }, { "word": "amazing!'", "start": 31.2, "end": 32.0 },
    { "word": "People", "start": 32.5, "end": 32.8 }, { "word": "are", "start": 32.8, "end": 33.0 },
    { "word": "noticing,", "start": 33.0, "end": 33.6 }, { "word": "and", "start": 33.7, "end": 33.8 },
    { "word": "my", "start": 34.2, "end": 34.4 }, { "word": "confidence", "start": 34.4, "end": 35.2 },
    { "word": "is", "start": 35.2, "end": 35.4 }, { "word": "through", "start": 35.4, "end": 35.7 },
    { "word": "the", "start": 35.7, "end": 35.8 }, { "word": "roof.", "start": 35.8, "end": 36.4 }
];

const PROCESSING_STEPS = [
    "Uploading your testimonial...",
    "Transcribing your powerful story...",
    "AI is analyzing for key moments...",
    "Identifying the hook, problem, and results...",
    "Assembling the most impactful clips...",
    "Rendering your final 9:16 reel in-browser...",
    "Adding finishing touches...",
];

interface Clip {
    category: string;
    text: string;
    start: number;
    end: number;
}

const App: React.FC = () => {
    const [status, setStatus] = useState<Status>(Status.Idle);
    const [videoFile, setVideoFile] = useState<File | null>(null);
    const [reelUrl, setReelUrl] = useState<string | null>(null);
    const [errorMessage, setErrorMessage] = useState<string>('');
    const [processingStep, setProcessingStep] = useState(0);

    const ai = useRef(
        process.env.API_KEY ? new GoogleGenAI({ apiKey: process.env.API_KEY }) : null
    ).current;

    const videoRef = useRef<HTMLVideoElement>(null);
    const canvasRef = useRef<HTMLCanvasElement>(null);

    const assembleReelOnClient = useCallback(async (sourceFile: File, playlist: Clip[]): Promise<string> => {
        return new Promise(async (resolve, reject) => {
            if (!videoRef.current || !canvasRef.current) {
                return reject(new Error("Video or Canvas refs not available"));
            }

            const video = videoRef.current;
            const canvas = canvasRef.current;
            const ctx = canvas.getContext('2d');
            if (!ctx) return reject(new Error("Could not get canvas context"));

            const videoUrl = URL.createObjectURL(sourceFile);
            video.src = videoUrl;
            
            await new Promise<void>(resolve_load => {
                video.onloadedmetadata = () => {
                    const targetAspectRatio = 9 / 16;
                    canvas.width = 540; // Standard reel width
                    canvas.height = canvas.width / targetAspectRatio;
                    resolve_load();
                };
            });
            
            const stream = canvas.captureStream(30); // 30 FPS
            const recorder = new MediaRecorder(stream, { mimeType: 'video/webm; codecs=vp9' });
            const chunks: Blob[] = [];

            recorder.ondataavailable = (e) => {
                if (e.data.size > 0) chunks.push(e.data);
            };

            recorder.onstop = () => {
                const blob = new Blob(chunks, { type: 'video/webm' });
                const url = URL.createObjectURL(blob);
                URL.revokeObjectURL(videoUrl);
                resolve(url);
            };
            
            recorder.onerror = (e) => reject(e);

            recorder.start();

            for (const clip of playlist) {
                await new Promise<void>(resolve_clip => {
                    let rafId: number;

                    const onSeeked = () => {
                        video.play();
                    };

                    const onPlay = () => {
                        const drawFrame = () => {
                            if (video.currentTime >= clip.end || video.paused) {
                                video.pause();
                                cancelAnimationFrame(rafId);
                                video.removeEventListener('play', onPlay);
                                video.removeEventListener('seeked', onSeeked);
                                resolve_clip();
                                return;
                            }
                           
                            // Letterbox/Pillarbox logic
                            const videoAspectRatio = video.videoWidth / video.videoHeight;
                            const canvasAspectRatio = canvas.width / canvas.height;
                            let dWidth, dHeight, dx, dy;

                            if (videoAspectRatio > canvasAspectRatio) {
                                // Video is wider than canvas -> letterbox (bars top/bottom)
                                dWidth = canvas.width;
                                dHeight = dWidth / videoAspectRatio;
                                dx = 0;
                                dy = (canvas.height - dHeight) / 2;
                            } else {
                                // Video is taller or same aspect as canvas -> pillarbox (bars left/right)
                                dHeight = canvas.height;
                                dWidth = dHeight * videoAspectRatio;
                                dy = 0;
                                dx = (canvas.width - dWidth) / 2;
                            }

                            // Fill background with black for the bars
                            ctx.fillStyle = 'black';
                            ctx.fillRect(0, 0, canvas.width, canvas.height);
                            
                            // Draw the video frame, scaled and centered
                            ctx.drawImage(video, 0, 0, video.videoWidth, video.videoHeight, dx, dy, dWidth, dHeight);

                            rafId = requestAnimationFrame(drawFrame);
                        };
                        rafId = requestAnimationFrame(drawFrame);
                    };

                    video.addEventListener('seeked', onSeeked, { once: true });
                    video.addEventListener('play', onPlay, { once: true });
                    video.currentTime = clip.start;
                });
            }

            recorder.stop();
        });
    }, []);

    const processVideoWithAI = useCallback(async () => {
        if (!videoFile) return;
        if (!ai) {
            setErrorMessage("Gemini AI client is not initialized. Make sure the API key is configured.");
            setStatus(Status.Error);
            return;
        }

        try {
            // STEP 1: (MOCKED) Transcription
            setProcessingStep(1);
            await new Promise(resolve => setTimeout(resolve, 1000));
            const transcript = MOCK_TRANSCRIPT_DATA;

            // STEP 2: AI Story-Finder Logic with Gemini
            setProcessingStep(2);

            const schema = {
                type: Type.OBJECT,
                properties: {
                    playlist: {
                        type: Type.ARRAY,
                        description: "An ordered list of video clips for the final reel, following the narrative structure.",
                        items: {
                            type: Type.OBJECT,
                            properties: {
                                category: { type: Type.STRING, description: "The category of the clip (e.g., 'Hook', 'Problem', 'Result_Metric', 'Result_Social')." },
                                text: { type: Type.STRING, description: "The exact transcript text of the clip." },
                                start: { type: Type.NUMBER, description: "The start time of the clip in seconds." },
                                end: { type: Type.NUMBER, description: "The end time of the clip in seconds." },
                            },
                            required: ['category', 'text', 'start', 'end'],
                        },
                    },
                },
                required: ['playlist'],
            };
            
            const prompt = `You are an expert video editor creating a viral social media reel from a weight loss testimonial. Analyze the provided transcript with word-level timestamps.
Your task is to identify clips for a 60-90 second video following the "Problem -> Turning Point -> Result" structure.

1.  **Hook**: Find a powerful 3-5 second emotional hook from the first 25% of the transcript. This should be a statement of past struggle.
2.  **Problem**: Find 1-2 clips describing the "before" state (e.g., weight, low energy).
3.  **Turning Point**: Find 1 clip that signifies the change.
4.  **Results**: Find 3-4 clips showcasing success. Prioritize clips with measurable data (e.g., "lost 20 kgs"), then social proof (e.g., "people are noticing").

Assemble these clips into a final playlist, ordered correctly (Hook, Problem, Turning Point, Results). The total duration should be between 20-45 seconds to keep it concise for this demo. Return ONLY the JSON object.

Transcript:
${JSON.stringify(transcript)}
`;
            
            setProcessingStep(3);
            const response = await ai.models.generateContent({
                model: 'gemini-2.5-flash',
                contents: prompt,
                config: {
                    responseMimeType: 'application/json',
                    responseSchema: schema,
                },
            });

            const result = JSON.parse(response.text);
            console.log("✅ AI Generated Playlist:", result.playlist);

            // STEP 3: Client-Side Video Assembly
            setProcessingStep(4);
            await new Promise(resolve => setTimeout(resolve, 1000));
            setProcessingStep(5);
            const finalReelUrl = await assembleReelOnClient(videoFile, result.playlist);
            
            setProcessingStep(6);
            await new Promise(resolve => setTimeout(resolve, 500));

            setReelUrl(finalReelUrl);
            setStatus(Status.Success);

        } catch (error) {
            console.error("Error processing video with AI:", error);
            const message = error instanceof Error ? error.message : "An unknown error occurred.";
            setErrorMessage(`Failed to analyze the video with AI. ${message}`);
            setStatus(Status.Error);
        }
    }, [videoFile, ai, assembleReelOnClient]);

    useEffect(() => {
        if (status === Status.Uploading) {
            setStatus(Status.Processing);
            processVideoWithAI();
        }
    }, [status, processVideoWithAI]);

    const handleFileSelect = useCallback((file: File) => {
        if (!file.type.startsWith('video/')) {
            setErrorMessage('Please upload a valid video file (MP4, MOV, etc.).');
            setStatus(Status.Error);
            return;
        }
        setErrorMessage('');
        setVideoFile(file);
        setStatus(Status.Uploading);
    }, []);

    const handleReset = useCallback(() => {
        if (reelUrl) {
            URL.revokeObjectURL(reelUrl);
        }
        setStatus(Status.Idle);
        setVideoFile(null);
        setReelUrl(null);
        setErrorMessage('');
        setProcessingStep(0);
    }, [reelUrl]);

    const renderContent = () => {
        switch (status) {
            case Status.Idle:
                return <FileUpload onFileSelect={handleFileSelect} isProcessing={false} />;
            case Status.Uploading:
            case Status.Processing:
                return <Loader messages={PROCESSING_STEPS} currentStep={processingStep} />;
            case Status.Success:
                if (reelUrl) {
                    return <ReelPlayer videoUrl={reelUrl} onReset={handleReset} />;
                }
                // Fallback to error if URL is missing
                setErrorMessage("Reel generated, but the URL is missing. Please try again.");
                setStatus(Status.Error);
                return null;
            case Status.Error:
                return (
                    <div className="text-center">
                        <h3 className="text-xl font-bold text-red-400 mb-4">Something went wrong</h3>
                        <p className="text-slate-400 mb-6">{errorMessage}</p>
                        <button
                            onClick={handleReset}
                            className="bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded-lg transition-colors"
                        >
                            Try Again
                        </button>
                    </div>
                );
            default:
                return null;
        }
    };

    return (
        <div className="min-h-screen flex flex-col items-center justify-center p-4 sm:p-6 bg-slate-900">
            {/* Hidden elements for client-side processing */}
            <video ref={videoRef} style={{ display: 'none' }} muted playsInline />
            <canvas ref={canvasRef} style={{ display: 'none' }} />

            <div className="w-full max-w-2xl mx-auto">
                <header className="text-center mb-10">
                    <h1 className="text-4xl sm:text-5xl font-extrabold text-white mb-3 flex items-center justify-center gap-3">
                        <SparklesIcon className="w-8 h-8 text-yellow-400" />
                        AI Reel Generator
                        <SparklesIcon className="w-8 h-8 text-yellow-400" />
                    </h1>
                    <p className="text-lg text-slate-400">
                        Transform weight loss testimonials into powerful, social-media-ready reels in seconds.
                    </p>
                </header>
                <main className="bg-slate-800/50 border border-slate-700 rounded-2xl p-8 shadow-2xl shadow-slate-950/50 backdrop-blur-sm">
                    {renderContent()}
                </main>
                 <footer className="text-center mt-8 text-slate-500 text-sm">
                    <p>Powered by Gemini & In-Browser Video Processing</p>
                </footer>
            </div>
        </div>
    );
};

export default App;